### ISSUE TITLE
sasl kerberos 

### ISSUE THREAD

**Issue by HamoonDBA** [weiboad/kafka-php#232]
Hello,
We use Apache Kafka 1.0.0.

Last week we launched Kerberos for our Apache Kafka server.

Everything is good and we can connect to Kafka with Python confluent kafka and setting sasl.kerberos property.

But when I set these configs for connecting to Kafka with kafka-php I get this Error:

`PHP Fatal error:  Uncaught exception 'Kafka\Exception' with message 'Unexpected EOF while reading 4 bytes from stream (no data)' in /root/x/vendor/nmred/kafka-php/src/Kafka/SocketSync.php:312
Stack trace:
#0 /root/x/vendor/nmred/kafka-php/src/Kafka/Producer/SyncProcess.php(127): Kafka\SocketSync->read(4)
#1 /root/x/vendor/nmred/kafka-php/src/Kafka/Producer/SyncProcess.php(46): Kafka\Producer\SyncProcess->syncMeta()
#2 /root/x/vendor/nmred/kafka-php/src/Kafka/Producer.php(54): Kafka\Producer\SyncProcess->__construct()
#3 /root/x/index.php(19): Kafka\Producer->__construct()
#4 {main}
  thrown in /root/x/vendor/nmred/kafka-php/src/Kafka/SocketSync.php on line 312
`
I want to produce to Kafka.

I Couldn't find anything about how can I solve this problem in PHP

**Comment by lcobucci** [comment]
@HamoonDBA could you please attach here the logs of the producer/consumer?

**Comment by HamoonDBA** [comment]
@lcobucci It was only of error I got to receive.

**Comment by HamoonDBA** [comment]
@lcobucci one thing.

I don't have Sasl directory in my src!

look at the picture

![sasl](https://user-images.githubusercontent.com/3939424/44021216-7cb83612-9ef9-11e8-98d8-ba45e0d8bb1f.jpg)

**Comment by lcobucci** [comment]
@HamoonDBA could you please try it with the development version (master branch)?

**Comment by HamoonDBA** [comment]
Thanks.

I found this file in the dev-master branch.

But I have another problem.

I don't find any method to set sasl.kerberos.service.name

**Comment by HamoonDBA** [comment]
@lcobucci I got this Error when I set Sasls Config:

`PHP Fatal error:  Uncaught Kafka\Exception\ConnectionException: It was not possible to establish a connection for metadata with the brokers "kafka2.dev:9094" in /home/kafka/vendor/nmred/kafka-php/src/Exception/ConnectionException.php:13
Stack trace:
#0 /home/kafka/vendor/nmred/kafka-php/src/Producer/SyncProcess.php(146): Kafka\Exception\ConnectionException::fromBrokerList('kafka2.dev:9094')
#1 /home/kafka/vendor/nmred/kafka-php/src/Producer/SyncProcess.php(38): Kafka\Producer\SyncProcess->syncMeta()
#2 /home/kafka/vendor/nmred/kafka-php/src/Producer.php(24): Kafka\Producer\SyncProcess->__construct()
#3 /home/kafka/index.php(27): Kafka\Producer->__construct()
#4 {main}
  thrown in /home/kafka/vendor/nmred/kafka-php/src/Exception/ConnectionException.php on line 13
`
I attached my code:


[kafka_producer.txt](https://github.com/weiboad/kafka-php/files/2290388/kafka_producer.txt)

**Comment by lcobucci** [comment]
@HamoonDBA I'm not 100% confident about my skills regarding SASL configuration in Kafka, could you share the config you're using on the broker so that we can try to reproduce this issue together using a docker container and add a functional test to the repository?

**Comment by HamoonDBA** [comment]
@lcobucci The error related to krb5 extension. I installed php-krb5 extension.

Now Sasl initSecContext returns true.

Sasl authenticate hand shake (Mechasnism Class, handShake Methdo) has No Error 

But in performAuthentication method, when it wants to read 4 blocks from readBlocking method, fread function return EOF instead of 4 bytes chunk .

I'm sure It's not related to Broker or kerberos server. because of another application which programming with Python and Java work correctly.

**Comment by HamoonDBA** [comment]
@lcobucci The error related to krb5 extension. I installed php-krb5 extension.

Now Sasl initSecContext returns true.

Sasl authenticate hand shake (Mechasnism Class, handShake Methdo) has No Error

But in performAuthentication method, when it wants to read 4 blocks from readBlocking method, $this->select return 0 and stream_get_meta_data return:

`Array
(
    [timed_out] =>
    [blocked] => 1
    [eof] =>
    [stream_type] => tcp_socket/ssl
    [mode] => r+
    [unread_bytes] => 0
    [seekable] =>
)
`

I'm sure It's not related to Broker or kerberos server. because of another application which programming with Python and Java work correctly.

**Comment by HamoonDBA** [comment]
@lcobucci The error related to krb5 extension. I installed php-krb5 extension.

Now Sasl initSecContext returns true.

Sasl authenticate hand shake (Mechasnism Class, handShake Methdo) has No Error

But in performAuthentication method, when it wants to read 4 blocks from readBlocking method, fread function return EOF instead of 4 bytes chunk, while writeBlocking didn't have any error, and it could write 573 bytes to the socket .

I'm sure It's not related to Broker or kerberos server. because of another application which programming with Python and Java work correctly.

**Comment by lcobucci** [comment]
@HamoonDBA I'm confident that it's related to the implementation here, unfortunately.
