### ISSUE TITLE
consumer demo error.

### ISSUE THREAD

**Issue by GavinZhao8** [weiboad/kafka-php#282]
`PHP Fatal error:  Uncaught Kafka\Exception\Protocol: unpack failed. string(raw) length is 0 , TO N in /mnt/d/WorkSpace/Projects/kafka-demo/vendor/nmred/kafka-php/src/Kafka/Protocol/Protocol.php:285
Stack trace:
#0 /mnt/d/WorkSpace/Projects/kafka-demo/vendor/nmred/kafka-php/src/Kafka/Protocol/Protocol.php(195): Kafka\Protocol\Protocol::checkLen('N', '')
#1 /mnt/d/WorkSpace/Projects/kafka-demo/vendor/nmred/kafka-php/src/Kafka/Protocol/Protocol.php(560): Kafka\Protocol\Protocol::unpack('N', '')
#2 /mnt/d/WorkSpace/Projects/kafka-demo/vendor/nmred/kafka-php/src/Kafka/Protocol/Fetch.php(301): Kafka\Protocol\Protocol->decodeString(false, 'N')
#3 /mnt/d/WorkSpace/Projects/kafka-demo/vendor/nmred/kafka-php/src/Kafka/Protocol/Fetch.php(236): Kafka\Protocol\Fetch->decodeMessage('%\x16\xE2\xB0\x00\x00test1.......', 23)
#4 [internal function]: Kafka\Protocol\Fetch->decodeMessageSet('\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x17%\x16\xE2...', 7166)
#5 /mnt/d/WorkSpace/Projects/kafka-demo/vendor/nmred/kafka-php/src/Kafka/Protocol/Fetch.p in /mnt/d/WorkSpace/Projects/kafka-demo/vendor/nmred/kafka-php/src/Kafka/Protocol/Protocol.php on line 285`

every config is default, expect ip and port, wha't wrong?

**Comment by lijoabraham** [comment]
@GavinZhao8 you can solve the error by updating the latest to kafka.
> http://mirror.linux-ia64.org/apache/kafka/2.3.1/kafka_2.12-2.3.1.tgz
