### ISSUE TITLE
This request is for a topic or partition that does not exist on this broker.

### ISSUE THREAD

**Issue by euskadi31** [weiboad/kafka-php#38]
Kafka Version: 0.8

``` php
<?php

$hosts = '...';

$consumer = \Kafka\Consumer::getInstance($hosts);
$consumer->setGroup('test_consumer');
$consumer->setFromOffset(true);
$consumer->setTopic('test', 0);
$result = $consumer->fetch();
foreach ($result as $topicName => $partition) {
    echo 'Topic: ' . $topicName . PHP_EOL;
    foreach ($partition as $partId => $messageSet) {
        echo 'PartitionId: ' . $partId . PHP_EOL;
        foreach ($messageSet as $message) {
            echo 'Message: ' . $message . PHP_EOL;
        }
    }
}
```

Output:

```
Topic: test
PartitionId: 0
Message: {"type":"test","timestamp":1444062734}
PHP Fatal error:  Uncaught exception 'Kafka\Exception' with message 'This request is for a topic or partition that does not exist on this broker.' in /home/acme/kafka/vendor/nmred/kafka-php/src/Kafka/Offset.php:181
Stack trace:
#0 /home/acme/kafka/vendor/nmred/kafka-php/src/Kafka/Protocol/Fetch/Helper/CommitOffset.php(114): Kafka\Offset->setOffset(0)
#1 /home/acme/kafka/vendor/nmred/kafka-php/src/Kafka/Protocol/Fetch/Helper/Helper.php(153): Kafka\Protocol\Fetch\Helper\CommitOffset->onPartitionEof(Object(Kafka\Protocol\Fetch\Partition))
#2 /home/acme/kafka/vendor/nmred/kafka-php/src/Kafka/Protocol/Fetch/MessageSet.php(168): Kafka\Protocol\Fetch\Helper\Helper::onPartitionEof(Object(Kafka\Protocol\Fetch\Partition))
#3 /home/acme/kafka/src/kafka_consumer.php(30): Kafka\Protocol\Fetch\MessageSet->valid()
#4 {main}
  thrown in /home/acme/kafka/vendor/nmred/kafka-php/src/Kafka/Offset.php on line 181
```

**Comment by nmred** [comment]
@euskadi31 
You can try using the new version.
