### ISSUE TITLE
持续发送消息时会丢失并且报 Uncaught LogicException: Cannot stop(); event reactor not currently active

### ISSUE THREAD

**Issue by kdlan** [weiboad/kafka-php#99]
```php
<?php

require __DIR__ . '/vendor/autoload.php';

$config = \Kafka\ProducerConfig::getInstance();
$config->setMetadataRefreshIntervalMs(10000);
$config->setMetadataBrokerList('dev-001:9092');
$config->setIsAsyn(false);
$config->setProduceInterval(500);
$config->setBrokerVersion('0.8.2.2');

while(true){
    $producer = new \Kafka\Producer(function() {
        return array(
            array(
                'topic' => 'zipkin_traces',
                'value' => '[]',
            ),
        );
    });
    $producer->success(function($result) {
        var_dump($result);
    });
    $producer->error(function($errorCode, $context) {
        var_dump($errorCode);
    });

    $producer->send();
    sleep(1);
}
```

输出

```
array(2) {
  ["throttleTime"]=>
  int(0)
  ["data"]=>
  array(1) {
    [0]=>
    array(2) {
      ["topicName"]=>
      string(13) "zipkin_traces"
      ["partitions"]=>
      array(1) {
        [0]=>
        array(4) {
          ["partition"]=>
          int(0)
          ["errorCode"]=>
          int(0)
          ["offset"]=>
          int(14)
          ["timestamp"]=>
          int(0)
        }
      }
    }
  }
}
array(2) {
  ["throttleTime"]=>
  int(0)
  ["data"]=>
  array(1) {
    [0]=>
    array(2) {
      ["topicName"]=>
      string(13) "zipkin_traces"
      ["partitions"]=>
      array(1) {
        [0]=>
        array(4) {
          ["partition"]=>
          int(2)
          ["errorCode"]=>
          int(0)
          ["offset"]=>
          int(14)
          ["timestamp"]=>
          int(0)
        }
      }
    }
  }
}
array(2) {
  ["throttleTime"]=>
  int(0)
  ["data"]=>
  array(1) {
    [0]=>
    array(2) {
      ["topicName"]=>
      string(13) "zipkin_traces"
      ["partitions"]=>
      array(1) {
        [0]=>
        array(4) {
          ["partition"]=>
          int(3)
          ["errorCode"]=>
          int(0)
          ["offset"]=>
          int(14)
          ["timestamp"]=>
          int(0)
        }
      }
    }
  }
}
array(2) {
  ["throttleTime"]=>
  int(0)
  ["data"]=>
  array(1) {
    [0]=>
    array(2) {
      ["topicName"]=>
      string(13) "zipkin_traces"
      ["partitions"]=>
      array(1) {
        [0]=>
        array(4) {
          ["partition"]=>
          int(2)
          ["errorCode"]=>
          int(0)
          ["offset"]=>
          int(14)
          ["timestamp"]=>
          int(0)
        }
      }
    }
  }
}
array(2) {
  ["throttleTime"]=>
  int(0)
  ["data"]=>
  array(1) {
    [0]=>
    array(2) {
      ["topicName"]=>
      string(13) "zipkin_traces"
      ["partitions"]=>
      array(1) {
        [0]=>
        array(4) {
          ["partition"]=>
          int(7)
          ["errorCode"]=>
          int(0)
          ["offset"]=>
          int(14)
          ["timestamp"]=>
          int(0)
        }
      }
    }
  }
}
array(2) {
  ["throttleTime"]=>
  int(0)
  ["data"]=>
  array(1) {
    [0]=>
    array(2) {
      ["topicName"]=>
      string(13) "zipkin_traces"
      ["partitions"]=>
      array(1) {
        [0]=>
        array(4) {
          ["partition"]=>
          int(0)
          ["errorCode"]=>
          int(0)
          ["offset"]=>
          int(14)
          ["timestamp"]=>
          int(0)
        }
      }
    }
  }
}
int(1000)
array(2) {
  ["throttleTime"]=>
  int(0)
  ["data"]=>
  array(1) {
    [0]=>
    array(2) {
      ["topicName"]=>
      string(13) "zipkin_traces"
      ["partitions"]=>
      array(1) {
        [0]=>
        array(4) {
          ["partition"]=>
          int(1)
          ["errorCode"]=>
          int(0)
          ["offset"]=>
          int(14)
          ["timestamp"]=>
          int(0)
        }
      }
    }
  }
}
int(1000)
Fatal error: Uncaught LogicException: Cannot stop(); event reactor not currently active in /Users/Faye/workspace/user-service-view/vendor/amphp/amp/lib/NativeReactor.php:138
Stack trace:
#0 /Users/Faye/workspace/user-service-view/vendor/amphp/amp/lib/functions.php(65): Amp\NativeReactor->stop()
#1 /Users/Faye/workspace/user-service-view/vendor/nmred/kafka-php/src/Kafka/Producer/Process.php(116): Amp\stop()
#2 /Users/Faye/workspace/user-service-view/vendor/amphp/amp/lib/NativeReactor.php(294): Kafka\Producer\Process->Kafka\Producer\{closure}('000000005825f5e...', NULL)
#3 /Users/Faye/workspace/user-service-view/vendor/amphp/amp/lib/NativeReactor.php(222): Amp\NativeReactor->executeTimers()
#4 /Users/Faye/workspace/user-service-view/vendor/amphp/amp/lib/NativeReactor.php(71): Amp\NativeReactor->doTick(false)
#5 /Users/Faye/workspace/user-service-view/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(NULL)
#6 /Users/Faye/workspace/user-service-view/vendor/nmred/kafka-php/src/Kafka/Producer.php(72): Amp\run()
#7  in /Users/Faye/workspace/user-service-view/vendor/amphp/amp/lib/NativeReactor.php on line 138
```

运行大概6~7次之后就会进入到 error 里面，errorCode=1000，kafka 里检查过消息是没有发出去，最后再抛出上面的异常

**Comment by kdlan** [comment]
环境  php 7.0.13 
MAC OS和 ubuntu 14.04下都能复现
kafka 0.8.2.2

**Comment by kdlan** [comment]
初步 debug 下来应该是某一次请求响应比较慢超过了`sleep(1)`的等待时间，然后下一次请求正常发出，执行了 `Amp\stop()`，这个时候上次的请求收到响应，再次调用 `Amp\stop()` 导致的

尝试把 [这里](https://github.com/weiboad/kafka-php/blob/master/src/Kafka/Producer/Process.php#L116)  修改成 `\Amp\cancel($watcherId);` 之后就能够正常发送了

对 amphp 不是很熟悉，不知道这样的修复是否正常，另外也发现 [这里](https://github.com/weiboad/kafka-php/blob/master/src/Kafka/Producer/State.php#L97) 的 watcher 数量会持续增加，有可能存在内存溢出的风险

**Comment by nmred** [comment]
@kdlan  我明白你的意思了，你是想持续的置到后台发送消息，这个你直接把 $config->setIsAsyn(false);
改为 true 就可以，php-kafka 会自动挂起，不用 while(1){sleep}操作

**Comment by nmred** [comment]
试一下，example 中的 Producer ,吧async参数修改一下， 你这样调用用法不对

**Comment by nmred** [comment]
@kdlan  对于目前你这种是用方式，满足不了需求，你提交的PR 也会出问题，因为 \Amp 是全局静态的，并且如果再while 中执行 sleep 会影响 amp 时间调度

目前临时解决办法：采用 0.1.6 版本 producer ，这个版本完全是同步
下一版我再把 旧版本的 producer 整理到 0.2.0

**Comment by kdlan** [comment]
使用0.1.6能够满足需求

**Comment by kyozhou** [comment]
同样的问题，不过0.1也有bug，会使实际运行时间增加几百毫秒（虽然打印microtime测试时很快）

**Comment by nmred** [comment]
@kyozhou 试着使用最新版本的同步方式发送消息

**Comment by yuqiandoudou** [comment]
你好，我现在也遇到了同样的问题，版本为v0.2.0.7，谢谢！

**Comment by denghuachengle** [comment]
最新版本 v0.2.0.8 ，也有这个问题，，这个问题不能在新版本解决吗？ 而且$config->setIsAsyn(false);这个参数也同样的有问题，只能为false,,为true则会重复发送第一条消息
